"""
Django settings for EventOrg project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'
print(f"DEBUG is set to: {DEBUG}")

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'grappelli',
    # 'material.admin',
    # 'material.admin.default',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # LocalApp
    'MusicEventOrg',

    # Third party App
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    # 'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_yasg',
    'chartjs',

    # # Django-admin-tools
    # 'admin_tools',
    # 'admin_tools.theming',
    # 'admin_tools.menu',
    # 'admin_tools.dashboard',
]
ADMIN_TOOLS_INDEX_DASHBOARD = 'MusicEventOrg.dashboard.CustomIndexDashboard'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EventOrg.urls'

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR / 'static')
]
STATIC_ROOT = BASE_DIR / 'staticfiles'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'MusicEventOrg/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

WSGI_APPLICATION = 'EventOrg.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('DB_NAME'),
        "USER": os.getenv('DB_USER'),
        "PASSWORD": os.getenv('DB_PASSWORD'),
        "HOST": os.getenv('DB_HOST'),
        "PORT": os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#  Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [

        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
LOGIN_REDIRECT_URL = '/'  # Redirect to the homepage after login
LOGOUT_REDIRECT_URL = '/accounts/login/'
# LOGOUT_REDIRECT_URL = 'logged-out'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Number of items per page
}

ESEWA_CONFIG = {
    'merchant_code': os.getenv('ESEWA_MERCHANT_CODE'),  # Replace with your eSewa merchant code
    'payment_url': 'https://uat.esewa.com.np/epay/main',  # Test environment URL
    'verification_url': 'https://uat.esewa.com.np/epay/transrec',  # Test verification URL
    'callback_url': 'http://yourdomain.com/esewa/callback/',  # Replace with your callback URL
}

PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID')  # Replace with your sandbox Client ID
PAYPAL_SECRET = os.getenv('PAYPAL_SECRET')        # Replace with your sandbox Secret
PAYPAL_MODE = 'sandbox'                      # Use 'live' for production
PAYPAL_CURRENCY = 'USD'                      # Adjust based on your needs
PAYPAL_RETURN_URL = 'http://localhost:8000/api/paypal/callback/?status=success'
PAYPAL_CANCEL_URL = 'http://localhost:8000/api/paypal/callback/?status=cancel'

# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'MusicEventOrg.backends.EmailBackend',  # Custom backend for email-based login
# ]

# MATERIAL_ADMIN_SITE = {
#     'HEADER': 'MusicEventOrg Admin',  # Custom header text
#     'TITLE': 'MusicEventOrg Dashboard',  # Custom title
#     'THEME': 'dark',  # Use 'light' or 'dark' theme
# }


# Grappelli settings
# GRAPPELLI_ADMIN_TITLE = "MusicEventOrg Admin"
# GRAPPELLI_SWITCH_USER = True
# GRAPPELLI_AUTOCOMPLETE_LIMIT = 10


MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
